config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  if defined? Debugbar
    mount Debugbar::Engine => Debugbar.config.prefix
  end

  root "search#index"

  get "mailbox", to: "mailbox#index"
  get "messages/:id", to: "message#view"

  get "login", to: "authentications#new"
  get "logout", to: "authentications#destroy"


  namespace :admin do

     namespace :utils do
       if Rails.env.development?
         mount LetterOpenerWeb::Engine, at: "/letter_opener"
       end

       mount MissionControl::Jobs::Engine, at: "/jobs"
       mount Blazer::Engine, at: "/blazer"
       mount Audits1984::Engine => "/console"
     end
   end

  resources :agents do
    member do
      get :activate
      get :deactivate
    end
  end

  get "admin", to: "admin#index"
  get "admin/agents", to: "admin#agents"
  get "admin/sessions", to: "admin#sessions"
  get "admin/messages", to: "admin#messages"

  resources :sessions
  resources :search
  resources :authentications
  resources :messages
  resources :mailbox

end

app/views/admin/agents.html.erb
<% content_for :title, "Historical Loans Data" %>

<div class="container-responsive px-4 pt-4 pb-4">
  <div class="box">

    <div class="search-container">
      <div class="field">
        <div class="control">
          <input class="input" type="text" placeholder="Begin searching..." />
        </div>
      </div>
    </div>

    <br>

    <div class="table-container">
      <table class="table is-hoverable">
        <thead>
          <tr>
            <th>ID</th>
            <th>Access Level</th>
            <th>Approved</th>
            <th>Codename</th>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% @agents.each do |agent| %>
            <tr class="<%= case agent.access_level
              when 'JASPER'
                'bg-quail'
              when 'agent'
                'bg-agent'
              when 'admin'
                'bg-admin'
              when 'superadmin'
                'bg-superadmin'
              else
                'bg-unknown'
              end %>">
                <td><%= agent.id %></td>
                <td>
                  <% case agent.access_level %>
                    <% when 'JASPER' %>
                      Quail
                    <% when 'agent' %>
                      Agent
                    <% when 'admin' %>
                      Admin
                    <% when 'superadmin' %>
                      Super Admin
                    <% else %>
                      Unknown
                  <% end %>
                </td>
                <td><%= agent.approved ? "✅" : "❌"  %></td>
                <td><%= agent.codename %></td>
                <td><%= agent.full_name %></td>
                <td><%= agent.email %></td>
                <td>
                     <% if agent.active? %>
                        <div class="btn-group">
                            <%= link_to 'Deactivate', deactivate_agent_path(agent.id), class: 'btn btn-sm btn-primary' %>
                        </div>
                    <% else %>
                        <%= link_to 'Activate', activate_agent_path(agent.id), method: :put, class: 'btn btn-sm btn-success' %>
                    <% end %>

                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style>
  .table-container {
    height: 80vh;
    overflow-y: auto;
  }

  .table thead th {
    position: sticky;
    top: 0;
    z-index: 1;
    background: white;
  }

  .btn-group .btn-sm {
    margin-right: 5px;
  }

  .btn-group .btn-sm:last-child {
    margin-right: 0;
  }

  /* Define background colors for different access levels */
  .bg-quail {
    background-color: #f6b8c4;
    /* #f6b8c4 */
  }

  .bg-agent {
    background-color: #d1e7dd;
    /* #d1e7dd  */
  }

  .bg-admin {
    background-color: #cfe2f3;
    /* #cfe2f3 */
  }

  .bg-superadmin {
    background-color: #f9cb9c
    /* #f9cb9c */
  }

  .bg-unknown {
    background-color: #e0e0e0;
  }
</style>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.querySelector('.search-container input');
    const table = document.querySelector('.table');
    const rows = table.querySelectorAll('tbody tr');

    searchInput.addEventListener('input', () => {
      const query = searchInput.value.toLowerCase();

      rows.forEach(row => {
        // Select only the specific columns: Codename (4th), Name (5th), and Email (6th)
        const codenames = row.cells[4].textContent.toLowerCase();
        const names = row.cells[5].textContent.toLowerCase();
        const emails = row.cells[6].textContent.toLowerCase();

        const match = codenames.includes(query) || names.includes(query) || emails.includes(query);

        row.style.display = match ? '' : 'none';
      });
    });
  });
</script>

app/views/admin/index.html.erb
<div class="container-responsive px-4 pt-4 pb-4">
  <div class="box" id="bx">
    <div class="columns" id="cl">
      <div class="column is-1">
        <%= link_to admin_agents_path, class: "btn btn-info rounded-pill shadow-sm" do %>
          <i class="fas fa-user-secret"></i>
        <% end %>
      </div>
      <div class="column is-1">
        <%= link_to admin_sessions_path, class: "btn btn-info rounded-pill shadow-sm" do %>
          <i class="fas fa-cubes-stacked"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>


<style>
#cl {
  display: flex;
  justify-content: flex-end;
  margin: 0;
}

.column {
  padding: 0;
  margin-left: -3vw
}

.column:last-child {
  margin-right: -3.5vw;
}

.btn-info:hover {
  background-color: #138496;
  border-color: #117a8b;
}

.rounded-pill {
  border-radius: 50rem;
}

.shadow-sm {
  box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075);
}
</style>

app/views/admin/messages.html.erb
<div class="container-responsive px-4 pt-4 pb-4">
  <div class="box">
      <h1>Messages</h1>
      <div class="table-container">
        <table class="table is-hoverable">
          <thead>
            <tr>
                <th>MID</th>
              <th>ID</th>
              <th>To</th>
            <th>From</th>
            <th>Subject</th>
            <th>Created At</th>
            <th>Num of Attachments</th>
            <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @messages.each do |message| %>
              <tr>
                <td><%= message.mailbox_id %></td>
                <td><%= message.id %></td>
                <td>
                  <% if message.to.size > 1 %>
                    <%= message.to.first %>....
                  <% else %>
                    <%= message.to.first %>
                  <% end %>
                </td>
                <td><%= message.from %></td>
                <td><%= message.subject %></td>
                <td><%= message.created_at %></td>
                <td><%= message.attachments.count %></td>
                <td>
                    <%= link_to message, class: "btn btn-info rounded-pill shadow-sm" do %>
                        <i class="fas fa-eye"></i>
                    <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 5px;
  border-bottom: 1px solid #ddd;
}

th {
  border-bottom: 2px solid #ddd;
}

.btn-danger {
  background-color: #dc3545;
  color: white;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
}

.btn-danger:hover {
  background-color: #c82333;
}
</style>

app/views/admin/sessions.html.erb
<div class="container-responsive px-4 pt-4 pb-4">
  <div class="box">
      <h1>Sessions</h1>
      <div class="table-container">
        <table class="table is-hoverable">
          <thead>
            <tr>
              <th>Session ID</th>
              <th>Created At</th>
              <th>CSRF Token</th>
              <th>Authentication Agent ID</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @sessions.each do |session| %>
              <tr>
                <td><%= session[:session_id][-14..-1] %></td>
                <td><%= session[:created_at].strftime("%B %d, %Y at %I:%M %p") %></td>
                <td><%= session.dig(:data, "_csrf_token") ? session.dig(:data, "_csrf_token")[-10..-1] : "N/A" %></td>
                <td><%= agent_codename(session.dig(:data, "current_authentication")&.instance_variable_get(:@agent_id)) || "Not Found" %></td>
                <td>
                    <!-- button to destroy session -->
                      <button class="btn btn-danger" type="submit">
                          <i class="fas fa-trash"></i>
                      </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 5px;
  border-bottom: 1px solid #ddd;
}

th {
  border-bottom: 2px solid #ddd;
}

.btn-danger {
  background-color: #dc3545;
  color: white;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
}

.btn-danger:hover {
  background-color: #c82333;
}
</style>