config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  if defined? Debugbar
    mount Debugbar::Engine => Debugbar.config.prefix
  end

  root "search#index"

  get "mailbox", to: "mailbox#index"
  get "messages/:id", to: "message#view"

  get "login", to: "authentications#new"
  get "logout", to: "authentications#destroy"


  namespace :admin do

     namespace :utils do
       if Rails.env.development?
         mount LetterOpenerWeb::Engine, at: "/letter_opener"
       end

       mount MissionControl::Jobs::Engine, at: "/jobs"
       mount Blazer::Engine, at: "/blazer"
       mount Audits1984::Engine => "/console"
     end
   end

  resources :agents do
    member do
      get :activate
      get :deactivate
    end
  end

  get "admin", to: "admin#index"
  get "admin/agents", to: "admin#agents"
  get "admin/sessions", to: "admin#sessions"
  get "admin/messages", to: "admin#messages"

  resources :sessions
  resources :search
  resources :authentications
  resources :messages
  resources :mailbox

end

app/models/authentication.rb
# frozen_string_literal: true

class Authentication
  def initialize(session, agent)
    session[:current_authentication] = self
    @agent_id = agent.id
  end

  def destroy(session)
    session[:current_authentication] = nil
    @agent_id = nil
  end

  def agent
    Agent.find_by(id: @agent_id)
  end

  def agent=(agent)
    @agent_id = agent.id
  end

end

app/controllers/authentications_controller.rb
# frozen_string_literal: true

class AuthenticationsController < ApplicationController
  before_action :ensure_authenticated, only: [:destroy]
  before_action :ensure_not_authenticated, only: [:new, :create]

  def new
    @agent = Agent.new

    if session[:current_authentication]
      redirect_to enter_path
    else
      render "new"
    end
  end

  def create
    @agent = Agent.find_by(email: auth_params[:email]) || Agent.find_by(agent_email: auth_params[:email])

    if @agent && @agent.authenticate(auth_params[:password])
       Authentication.new(session, @agent)
       redirect_to root_path
     else
       flash[:danger] = "Login failed. Please try again."
       render "new"
     end
  end

  def destroy
    session[:current_authentication].destroy(session)
    redirect_to login_path
  end

  private

  def auth_params
    params.require(:agent).permit(:email, :password)
  end

end

app/controllers/helpers/users/authentications_helper.rb
# frozen_string_literal: true

module Users
  module AuthenticationsHelper
  end
end

app/views/authentications/new.html.erb
<% content_for :title, "Sign In" %>

<div class="container px-2">
  <div class="box">
    <%= form_with url: authentications_path, scope: :agent, local: true do |form| %>
      <div class="creds">
        <p>Enter your credentials to gain access...</p>
      </div>
      <br />
      <div class="pb-3">
        <%= form.label :email %>
        <%= form.email_field :email, required: true, class: "input" %>
      </div>
      <div>
        <%= form.label :password %>
        <%= form.password_field :password, required: true, class: "input" %>
      </div>
      <br />
      <%= form.submit "Login", class: "button is-success" %>
    <% end %>
  </div>
</div>

<style>
  .container {
    position: absolute;
    top: 45%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
</style>