config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  if defined? Debugbar
    mount Debugbar::Engine => Debugbar.config.prefix
  end

  root "search#index"

  get "mailbox", to: "mailbox#index"
  get "messages/:id", to: "message#view"

  get "login", to: "authentications#new"
  get "logout", to: "authentications#destroy"


  namespace :admin do

     namespace :utils do
       if Rails.env.development?
         mount LetterOpenerWeb::Engine, at: "/letter_opener"
       end

       mount MissionControl::Jobs::Engine, at: "/jobs"
       mount Blazer::Engine, at: "/blazer"
       mount Audits1984::Engine => "/console"
     end
   end

  resources :agents do
    member do
      get :activate
      get :deactivate
    end
  end

  get "admin", to: "admin#index"
  get "admin/agents", to: "admin#agents"
  get "admin/sessions", to: "admin#sessions"
  get "admin/messages", to: "admin#messages"

  resources :sessions
  resources :search
  resources :authentications
  resources :messages
  resources :mailbox

end

app/views/layouts/_footer.html.erb
<footer>
  <% if greenhouse_version != "DEVELOPMENT" %>
    <div id="foot-prod">
      <div class="footer-content prod-color">
        <p>
          <%= help_message %>
          <% if commit_hash.present? %>
            <% if commit_duration.present? %>
              Running build <em aria-label="<%= commit_hash %>" class="tooltipped tooltipped--n tooltipped--lg"><%= commit_name %></em>
              from <%= commit_duration %> ago.
            <% else %>
              Build <em aria-label="<%= commit_hash %>" class="tooltipped tooltipped--n tooltipped--lg"><%= commit_name %></em>.
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  <% else %>
    <div id="foot-dev">
      <div class="footer-content dev-color">
        <p><b>DEVELOPMENT ENV</b> || Rails: <i><%= Rails::VERSION::STRING %></i> | Ruby: <i><%= ruby_version %></i> | SHA: <i><%= commit_name %></i> || <b>DEVELOPMENT ENV</b></p>
      </div>
    </div>
  <% end %>
</footer>

<style>
#foot-prod, #foot-dev {
    position: fixed;
    bottom: 1vh;
    left: 1vw;
    width: 98vw;
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0;
}

.footer-content {
    padding: 10px 35px; /* Adjust padding as needed */
    display: inline-block;
    border-radius: 8px; /* Optional: for rounded corners */
}

.prod-color {
    background-color: hsl(0, 0%, 100%); /* White color in HSL */
}

.dev-color {
    background-color: hsl(0, 71%, 63%); /* Red color in HSL */
}

#foot-prod p, #foot-dev p {
    margin: 0;
}
</style>

app/views/layouts/_unsupported_browser_warning.html.erb
body
- if !supported_browser?
render 'layouts/unsupported_browser_warning'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="194x194" href="/favicon-194x194.png" />
    <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#4a856b" />
    <meta name="msapplication-TileColor" content="#4a856b" />
    <meta name="apple-mobile-web-app-title" content="The Greenhouse" />
    <meta name="application-name" content="The Greenhouse" />
    <meta name="msapplication-TileImage" content="/mstile-144x144.png" />
    <meta name="theme-color" content="#4a856b" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>
      <%= yield(:title).concat(" ~") if content_for?(:title) %> Greenhouse
    </title>

    <link rel="canonical" href="https://greenhouse.directory/" />
    <meta name="description" content="" />
    <%= yield(:head) if content_for?(:head) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbo-track': "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://kit.fontawesome.com/96163f3b63.js" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>

    <!-- Display flash messages -->
    <% flash.each do |type, message| %>
      <div class="notification is-<%= type %>">
        <button class="delete" onclick="(this.parentNode.remove())"></button>
        <%= message %>
      </div>
    <% end %>

    <!-- Conditional footer rendering -->
    <% unless [root_path, mailbox_path, admin_path, admin_agents_path, admin_sessions_path, admin_messages_path].include?(request.path) %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>

  <script>
    console.log(`%c
     ______                                 __
     .' ___  |                               [  |
    / .'   \\_| _ .--.  .---.  .---.  _ .--.   | |--.   .--.   __   _   .--.  .---.
    | |   ____[ \`/'\\]/ /__\\\\/ /__\\\\[ \`.-. |  | .-. |/ .'\\ \\[  | | | ( (\`\\]/ /__\\\\
    \\ \`.___]  || |    | \\__.,| \\__., | | | |  | | | || \\__. | | \\_/ |, \`'.'.| \\__.,
     \`._____.'[___]    '.__.' '.__.'[___||__][___]|__]'.__.'  '.__.'_/[\\__) )'.__.'

     Loaded greenhouse.directory in env: <%= greenhouse_version %>
    `, 'color: #4a856b; font-weight: bold;');
  </script>

  <style>
  /* @font-face {
    font-family: "Ojuju";
    font-style: normal;
    font-weight: 400;
    src: url(<%= asset_path 'Ojuju-VariableFont_wght.ttf' %>) format("truetype");
  }
  */

    body {
      font-family: "Ojuju", system-ui;
      height: 100vh;
      width: 100vw;
      background-image: url(<%= asset_path 'background.svg' %>);
      background-repeat: no-repeat;
      background-size: cover;
    }

    .notification {
      position: absolute;
      top: .5rem;
      right: .5rem;
    }
  </style>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
      (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        const $notification = $delete.parentNode;

        $delete.addEventListener('click', () => {
          $notification.parentNode.removeChild($notification);
        });
      });
    });

    document.addEventListener('DOMContentLoaded', () => {
      const flash = document.getElementById('flash');
      if (flash) {
        setTimeout(() => {
          flash.remove();
        }, 5000);
      }
    });
  </script>

</html>